### ISSUE TITLE
CSS Overflow is Clearly Not Set for the Sidebar

### ISSUE THREAD

**Issue by Thomashighbaugh** [awesomeWM/awesome-www#163]
![20211121_195045](https://user-images.githubusercontent.com/32242061/142798942-6de195f9-17ac-4f83-9650-79b4ade9ac9d.png)

# Clearly Something is Wrong!

Not only is it somewhat hard to understand the vast majority of the documentation pages because they lack examples that coherently demonstrate the usage of whatever it is you found yourself looking at in an actual context users could find themselves in (*which is hard to write in the source code comments the docs are being generated from, but some pages seem to manage, so shouldn't that be added to the contribution requirements of the source code?*)...

**but someone did not appropriately set up the sidebar's overflow in CSS**

------

## Solution? Solution!

I would fix this myself, but I am busy at the moment with my config, a project that's gone on for years now and I would like to finish it, so you will have to wade through the css that is applied to what is pulled out of source code and smashed into the documentation site but I can help you with the specific rule you will need to add to the appropiate selector at least. 

### What It Will Look Like in Code

```css
.whatever-the-selector-is-called {
// ...other random css
overflow: auto;
// or
overflow: hidden 
}
```

### Current State's Probable CSS

its probably set to `visible` now, which is fine if you don't mind the bleed over I highlighted in my screenshot but personally I can't stand that. 

### CSS Selector Replacement Rationale 

- `auto` - adds scrollbars if needed (almost never actually needed, but in case you just **have to read the link in the little sidebar space**)

- `hidden` - because its a link, this works since hovering over the link will make its content appear if not in a popup, on the bottom `status bar` of most browsers. This should be enough for most people 

### That's It

Either prevents the bleed over that cannot be read by anyone, regardless of preference.

**Comment by Elv13** [comment]
I think you are using custom fonts override and you are looking at the old doc. What you see isn't what other people see.

https://awesomewm.org/apidoc/core_components/client.html

![image](https://user-images.githubusercontent.com/340384/142828704-04fa259e-84d4-45d7-8108-e79144fb9737.png)

**Comment by actionless** [comment]
they should be scrollable in the latest apidoc, in case if it doesnt fit:
![2021-11-22--1637610204_310x851_scrot](https://user-images.githubusercontent.com/1655669/142924937-f68f94d7-f93e-486a-ac80-d45303aefaa9.png)

**Comment by Aire-One** [comment]
@Thomashighbaugh probably don't know how we are working, so here are some additional information :

The API documentation is generated from our source code at [awesomewm/awesome](https://github.com/awesomeWM/awesome). The documentation you can read at https://awesomewm.org/doc/api/index.html was built against the stable version when it was released (almost 4 years ago now?).

Since then, we are still working on the git version and the doc evolved a lot. The new version has fixes for your reported bug : Sections names are wrapped and module names (that can't be break) are scrollable (see Elv and Actionless screenshots).

I'll consider this issue resolved and close it.
