### ISSUE TITLE
New AwesomeWM Website (2022)

### ISSUE THREAD

**Issue by raven2cz** [awesomeWM/awesome-www#174]
We already talk about it in #161, but the topic was about development environment, not directly focused to the website. I thought about it longer time and try to find some good solution for it. 

### Features
There are some features which can be expected from new website
* New professional theme in dark mode
* Main page with complete overview, descriptions, features, links. And big **Get Started** button for next actions and new users to continue with AW
* In Top menu: Welcome, Docs, Recipes, Showcase, [Blog], Community, Github
* Template fast driven webpage design
* Markdown for fast edition of pages
* Good administration of website - updates, backup, user access
* Long-term framework and basement for pages

### Tasks
* Rewrite actual website to new style. 
* Provides basic tutorials, installation guides in markdown; linkage to the awesome framework documentation.

### Framework for building websites 

There are many choices. I was pleased with several solutions and a certain firm decision was not made.

However, I really like this solution

* [**Doks**](https://getdoks.org/) Modern Documentation Theme. Look to Showcase tab too! 
* Doks is theme, open source project based on the [**HUGO**](https://gohugo.io/) - framework for building websites.

### About Hugo

Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. This means that, unlike systems like WordPress, Ghost and Drupal, which run on your web server expensively building a page every time a visitor requests one, Hugo does the building when you create your content. Since websites are viewed far more often than they are edited, Hugo is optimized for website viewing while providing a great writing experience.

Sites built with Hugo are extremely fast and very secure. Hugo sites can be hosted anywhere, including Heroku, GoDaddy, DreamHost, GitHub Pages, Google Cloud Storage, Amazon S3 and CloudFront, and work well with CDNs. Hugo sites run without dependencies on expensive runtimes like Ruby, Python or PHP and without dependencies on any databases.

We think of Hugo as the ideal website creation tool. With nearly instant build times and the ability to rebuild whenever a change is made, Hugo provides a very fast feedback loop. This is essential when you are designing websites, but also very useful when creating content.

### Conclusion

* I don't know who is hosting the current offline pages now. Can server support libs and technology necessary for Doks?
* What are your ideas about this change?
* How can decide if this change can be realized? 
* I can start with some first prototypes, demos. It depends on main dev team. Provide some opinions and actions which have to be make.

**Comment by Elv13** [comment]
> I don't know who is hosting the current offline pages now. Can server support libs and technology necessary for Doks?

It's hosted by GitHub. The pages are generated by GitHub actions and it supports installing things.

> What are your ideas about this change?

Why a new framework? We already use markdown and have some flexibility.

Also, why in general can't someone just iterate the current website? It doesn't feel like any of the proposed additions require any changes. New CSS is just a file. The other things are just minor changes to the content. The landing page layout is pretty much 15 years old, so while the content is fine, I agree that the presentation isn't really ideal.

As for `"Good administration of website - updates, backup, user access"`, I don't think this is a problem right now. It uses `git`/`github` for those 3 things. I am not inclined in changing that. Same for `"Long-term framework and basement for pages"`, this isn't a problem right now.

> How can decide if this change can be realized?

AwesomeWM is fueled by contributions. The best way to make something happen is to make it happen. Some stuff are big no-no, like JavaScript heavy pages which wont render for people who use noscript. Anything that depends on long running servers, CDN or cloud APIs (other than GitHub) is also a no. Anything that requires maintenance is discouraged, because nobody will realistically do it. Then it has to be free software all the way down (other than GitHub).

> I can start with some first prototypes, demos. It depends on main dev team. Provide some opinions and actions which have to be make.

It has to use GitHub actions and provide real benefits. A starting point might be to make the showcase part work properly. That means using the GitHub API to get the content of https://github.com/awesomeWM/awesome/issues/1395. It also probably means a bot to crawl reddit.com/r/unixporn and Discord for the screenshots, because it's really where the good stuff is posted these days.

It might also be worth iterating the current website with the new content before making any tech changes. It's markdown either way, so the content should be drop-in compatible.

> Provides basic tutorials, installation guides in markdown; linkage to the awesome framework documentation.

They already exist in the official doc and the 3rd part recipe section. I would prefer those topics not to proliferate across more locations. There must be a very good reason why a first party doc isn't part of the official (ldoc) doc. Last time we upgraded the website, my vote was to merge everything into the "framework doc". While ldoc sucks in pretty much every possible way, it's convenient for the users to have a single place for everything.

**Comment by raven2cz** [comment]
@Elv13 thanks for answer. So I will try to summarize your requirements. Please check if it is correct or there will be some misunderstanding or addition of something else.

### Requirements

#### Tech-Stack

* Pages hosted by Github and generated by GitHub actions.
* Updates, backup, user access rights are not necessary. All is stored in github git. If there is necessary some change, the PR has to be used and rebuild with github actions have to be performed.
* [ikiwiki](https://ikiwiki.info/) and [PerlMagick](https://www.imagemagick.org/script/perl-magick.php) are required for markdown support and for images. The pages will be still based on `ikiwiki` approach. 

Tech-stack remains original.

#### Theme, Style and Graphics
* [local.css](https://github.com/awesomeWM/awesome-www/blob/master/local.css), improve styling, theme, images to actual standards.

#### Page Content
* Welcome 
  * Add button: Get Started
  * Add button: Documentation
  * Add button: Download
  * Keep main definition of Awesomewm
  * Better section: Features
  * Better section: Why use AwesomeWM?
  * Better section: News - Crawler for closed issue (open topic), optional
* Showcase
  * Crawler for github issue #1395
  * Crawler for reddit.com/r/unixporn
  * Crawler for Awesomewm Discord channel
* Recipes - improve visualization and clarity. Missing actual "linkage with"  [awesome github](https://github.com/Thomashighbaugh/Awesome-AwesomeWM-Modules-Widgets-And-Libraries). It seems that there are more opinions against actual www page and github styling. See discuss here too: [reddit discussion](https://www.reddit.com/r/awesomewm/comments/wid67d/i_made_an_awesome_list_of_modules_libraries_and/)
* Other pages and content - minimal changes, just visualization

Documentation and Get Started buttons have to be links to Awesome ldoc documentation pages, because there is a requirement that introduction, first steps etc. will be part of ldoc.

**Comment by actionless** [comment]
to make the scope more clear, i recommend re-opening a new ticket for the remaining items
